[package]
name = "grrs"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "=4.5.49", features = ["derive"] }
anyhow = "1.0.101"
indicatif = "0.18.4"
log = "0.4.29"

[dev-dependencies]
assert_cmd = "2.0.14"
predicates = "3.1.0"
assert_fs = "1.1.1"
